unpackaged/main/default/objects/Opportunity_Product_Benefits__c/Opportunity_Product_Benefits__c.object-meta.xml
<CustomObject>
    <description>Custom object to track sponsorship opportunity benefits</description>
    <label>Opportunity Product Benefit</label>
    <nameField>
        <displayFormat>OPB{000000}</displayFormat>
        <label>Opportunity Product Benefits ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Opportunity_Product_Benefits__c/fields/FS_Benefit_Name__c.field-meta.xml
<CustomField>
    <fullName>FS_Benefit_Name__c</fullName>
    <label>Benefit Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/FS_Opportunity_Product_BenefitsTest.cls
/**
 * Created by Nikhil on 17-11-2019.
 */

@IsTest
public class FS_Opportunity_Product_BenefitsTest {
    @TestSetup
    private static void install() {
        Framework.Installer.install();
        PagesApi.PackageScripts.install();
        OrderApi.PackageScripts.install();

        Framework.RoutingRule[] rules = new List<Framework.RoutingRule>();
        Framework.RoutingRule FS_OppProductBenefitRule = new Framework.RoutingRule();
        FS_OppProductBenefitRule.apexClass = FS_Opportunity_Product_Benefits.class.getName();
        FS_OppProductBenefitRule.namespace = '';
        FS_OppProductBenefitRule.isEnabled = true;
        FS_OppProductBenefitRule.sObjectName = 'Opportunity_Product_Benefits__c';
        FS_OppProductBenefitRule.executionOrder = 0;
        rules.add(FS_OppProductBenefitRule);
        Framework.Config.push(rules);
    }
    @Istest
    static void oppProductBenefitInsert(){
        List<Opportunity_Product_Benefits__c> oppProdBenefitsList = new List<Opportunity_Product_Benefits__c>();
        Opportunity_Product_Benefits__c oppProdBenefits = new Opportunity_Product_Benefits__c(FS_Benefit_Name__c='Test Opportunity Benefit Name');
        oppProdBenefitsList.add(oppProdBenefits);
        insert oppProdBenefitsList;

        FS_Opportunity_Product_Benefits FS_oppProdBenefitsRule = new FS_Opportunity_Product_Benefits(oppProdBenefitsList);
        FS_Opportunity_Product_Benefits.Constructor oppProdB = new FS_Opportunity_Product_Benefits.Constructor();
        oppProdB.construct(oppProdBenefitsList);
        Framework.Dispatcher.dispatchTrigger();
    }
}