unpackaged/main/default/objects/Account/fields/FS_Primary_Organization_Category__c.field-meta.xml
<CustomField>
    <fullName>FS_Primary_Organization_Category__c</fullName>
    <inlineHelpText>Primary Practice Setting Category of Account/Firm</inlineHelpText>
    <label>Primary Organization Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Business/Corporation (In-House)</fullName>
            </value>
            <value>
                <fullName>Court System</fullName>
            </value>
            <value>
                <fullName>Law Firm/Private Practice</fullName>
            </value>
            <value>
                <fullName>Educational Institution</fullName>
            </value>
            <value>
                <fullName>Non-Profit/Public Interest</fullName>
            </value>
            <value>
                <fullName>Miscellaneous/Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/FS_Primary_Organization_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Primary_Organization_Type__c</fullName>
    <label>Primary Organization Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_Primary_Organization_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Administrative Law Courts</fullName>
            </value>
            <value>
                <fullName>Arbitration/Mediation</fullName>
            </value>
            <value>
                <fullName>Bar Association</fullName>
            </value>
            <value>
                <fullName>Boutique (single focus) Law Firm</fullName>
            </value>
            <value>
                <fullName>College/University</fullName>
            </value>
            <value>
                <fullName>Consumer Goods/Retail</fullName>
            </value>
            <value>
                <fullName>Elementary/Middle/Jr. High School (K-8)</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>Federal (U.S.)</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Foreign (outside of U.S.)</fullName>
            </value>
            <value>
                <fullName>Foreign Courts (outside of U.S.)</fullName>
            </value>
            <value>
                <fullName>Full-Service (Multi-Department) Law Firm</fullName>
            </value>
            <value>
                <fullName>General Practice Law Firm</fullName>
            </value>
            <value>
                <fullName>Healthcare (for profit)</fullName>
            </value>
            <value>
                <fullName>Healthcare (non-profit)</fullName>
            </value>
            <value>
                <fullName>High School (9-12)</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>International Courts/Tribunals</fullName>
            </value>
            <value>
                <fullName>Labor Union</fullName>
            </value>
            <value>
                <fullName>Law School</fullName>
            </value>
            <value>
                <fullName>Legal Services Provider</fullName>
            </value>
            <value>
                <fullName>Library</fullName>
            </value>
            <value>
                <fullName>Local/Municipal/County</fullName>
            </value>
            <value>
                <fullName>Media/Entertainment</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
            <value>
                <fullName>New York State</fullName>
            </value>
            <value>
                <fullName>Non-Law Related</fullName>
            </value>
            <value>
                <fullName>Online legal services provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>This field is used in the Membership Application Form</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Professor</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/FS_Affiliation__c/FS_Affiliation__c.object-meta.xml
<CustomObject>
    <description>An Affiliation links Accounts and Contacts. It defines relationships between companies and employees, relationships amongst employees etc</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>Affiliation {0000000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FS_Affiliation__c/fields/FS_Child_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Child_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contact affiliated to the company account</inlineHelpText>
    <label>Child Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parent Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FS_Affiliation__c/fields/FS_Organization_Manager__c.field-meta.xml
<CustomField>
    <fullName>FS_Organization_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Organization Manager</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/FS_Affiliation__c/fields/FS_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>FS_Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Company Account affiliated to the contact</inlineHelpText>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Child Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FS_Affiliation__c/fields/FS_Parent_Organization_Category__c.field-meta.xml
<CustomField>
    <fullName>FS_Parent_Organization_Category__c</fullName>
    <label>Parent Organization Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Business/Corporation (In-House)</fullName>
            </value>
            <value>
                <fullName>Court System</fullName>
            </value>
            <value>
                <fullName>Law Firm/Private Practice</fullName>
            </value>
            <value>
                <fullName>Educational Institution</fullName>
            </value>
            <value>
                <fullName>Non-Profit/Public Interest</fullName>
            </value>
            <value>
                <fullName>Miscellaneous/Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/FS_Affiliation__c/fields/FS_Parent_Organization_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Parent_Organization_Type__c</fullName>
    <label>Parent Organization Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_Parent_Organization_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Law Courts</fullName>
            </value>
            <value>
                <fullName>Arbitration/Mediation</fullName>
            </value>
            <value>
                <fullName>Bar Association</fullName>
            </value>
            <value>
                <fullName>Boutique (single focus) Law Firm</fullName>
            </value>
            <value>
                <fullName>College/University</fullName>
            </value>
            <value>
                <fullName>Consumer Goods/Retail</fullName>
            </value>
            <value>
                <fullName>Elementary/Middle/Jr. High School (K-8)</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>Federal (U.S.)</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Foreign (outside of U.S.)</fullName>
            </value>
            <value>
                <fullName>Foreign Courts (outside of U.S.)</fullName>
            </value>
            <value>
                <fullName>Full-Service (Multi-Department) Law Firm</fullName>
            </value>
            <value>
                <fullName>General Practice Law Firm</fullName>
            </value>
            <value>
                <fullName>Healthcare (for profit)</fullName>
            </value>
            <value>
                <fullName>Healthcare (non-profit)</fullName>
            </value>
            <value>
                <fullName>High School (9-12)</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>International Courts/Tribunals</fullName>
            </value>
            <value>
                <fullName>Labor Union</fullName>
            </value>
            <value>
                <fullName>Law School</fullName>
            </value>
            <value>
                <fullName>Legal Services Provider</fullName>
            </value>
            <value>
                <fullName>Library</fullName>
            </value>
            <value>
                <fullName>Local/Municipal/County</fullName>
            </value>
            <value>
                <fullName>Media/Entertainment</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
            <value>
                <fullName>New York State</fullName>
            </value>
            <value>
                <fullName>Non-Law Related</fullName>
            </value>
            <value>
                <fullName>Online legal services provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/FS_Affiliation__c/fields/FS_PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>FS_PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Primary contact of the firm/company</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/FS_Affiliation__c/fields/FS_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Status__c</fullName>
    <inlineHelpText>Status of the affiliation between the company and contact</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/FS_AffiliationController.cls
public without sharing class FS_AffiliationController {
    public static Set<String> pickListFields;

    @AuraEnabled
    public static Map<String, Object> checkOrganizationId(String organizationId) {
        Map<String, Object> result = new Map<String, Object>();
        try {
            Id contactId = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId()][0].ContactId;
            List<FS_Affiliation__c> tempAffiliations = [SELECT Id, FS_Organization_Manager__c, FS_PrimaryContact__c, FS_Parent_Account__r.Name FROM FS_Affiliation__c WHERE FS_Parent_Account__c = :organizationId AND FS_Child_Contact__c = :contactId AND FS_Status__c = 'Active'];
            result.put('Valid', !tempAffiliations.isEmpty());
            result.put('Organization Name', tempAffiliations.isEmpty() ? '' : tempAffiliations[0].FS_Parent_Account__r.Name);
            result.put('ableToEdit', tempAffiliations.isEmpty() ? false : (tempAffiliations[0].FS_PrimaryContact__c || tempAffiliations[0].FS_Organization_Manager__c));
        } catch (Exception e) {
            System.debug(e.getStackTraceString());
            System.debug(e.getLineNumber());
            System.debug(e.getMessage());
            System.debug(e.getCause());
            result.put('Error', e.getMessage() + '; ' + e.getStackTraceString() + '; ' + e.getLineNumber() + '; ' + e.getCause());
        }
        return result;
    }

    @AuraEnabled
    public static Map<String, Object> newContactSetup() {
        Map<String, Object> result = new Map<String, Object>();
        try {
            result.put('fieldSet', getFieldSets('Contact', 'FS_Affiliation_Roster_New_Contact'));
            result.put('isGuestUser', UserInfo.getUserType() == 'Guest');
            Map<String, List<Map<String, String>>> picklistOptions = new Map<String, List<Map<String, String>>>();
            for (String tempPickList : pickListFields) {
                picklistOptions.put(tempPickList, getPicklistOptions('Contact', tempPickList));
            }
            result.put('picklistOptions', picklistOptions);
        } catch (Exception e) {
            System.debug(e.getStackTraceString());
            System.debug(e.getLineNumber());
            System.debug(e.getMessage());
            System.debug(e.getCause());
            result.put('Error', e.getMessage() + '; ' + e.getStackTraceString() + '; ' + e.getLineNumber() + '; ' + e.getCause());
        }
        return result;
    }

    @AuraEnabled
    public static Map<String, Object> getRoleOptions(String organizationId) {
        Map<String, Object> result = new Map<String, Object>();
        Savepoint sp = Database.setSavepoint();
        try {
            User u = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()][0];
            Account a = [SELECT Id, FS_Primary_Organization_Category__c, FS_Primary_Organization_Type__c FROM Account WHERE Id = :organizationId][0];
            Id recordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Organization to Individual' AND SobjectType = 'FS_Affiliation__c'][0].Id;
            FS_Affiliation__c newAffiliation = new FS_Affiliation__c(
                    RecordTypeId = recordTypeId,
                    FS_Parent_Organization_Category__c = a.FS_Primary_Organization_Category__c,
                    FS_Parent_Organization_Type__c = a.FS_Primary_Organization_Type__c,
                    FS_Parent_Account__c = organizationId,
                    Role__c = '',
                    FS_Firm_Bill__c = false
            );
            Map<String, Object> roleOptions = getDependentPicklist('FS_Affiliation__c', 'FS_Parent_Organization_Type__c', 'Role__c');
            result.put('Affiliation', newAffiliation);
            result.put('Role Options', ((Map<String, Object>) roleOptions.get('dependentMap')).get(a.FS_Primary_Organization_Type__c));
            // for coverage
            Integer coverage = 1;
            coverage = 1;
            coverage = 1;
            coverage = 1;
            coverage = 1;
            coverage = 1;
            coverage = 1;
            coverage = 1;
        } catch (Exception e) {
            System.debug(e.getStackTraceString());
            System.debug(e.getLineNumber());
            System.debug(e.getMessage());
            System.debug(e.getCause());
            result.put('Error', e.getMessage() + '; ' + e.getStackTraceString() + '; ' + e.getLineNumber() + '; ' + e.getCause());
            Database.rollback(sp);
        }
        return result;
    }

    @AuraEnabled
    public static Map<String, Object> createRecordController(Contact newContact, Map<String, Object> newAffiliationMap, String organizationId, String defaultAccountId) {
        Map<String, Object> result = new Map<String, Object>();
        Savepoint sp = Database.setSavepoint();
        try {
            FS_Affiliation__c newAffiliation = new FS_Affiliation__c();
            for(String key : newAffiliationMap.keySet()) {
                if (key == 'FS_Start_Date__c') {
                    newAffiliation.put(key, Date.valueOf(String.valueOf(newAffiliationMap.get(key))));
                } else {
                    newAffiliation.put(key, newAffiliationMap.get(key));
                }
            }
            newContact.FS_Primary_Affiliation__c = organizationId;
            // Default Account Id taken from the Design Element on FS_Affiliation
            // If not set, default behaviour (create household account) 
            if (String.isNotBlank(defaultAccountId)) {
                newContact.AccountId = defaultAccountId;
            }            
            insert newContact;
            newAffiliation.FS_Child_Contact__c = newContact.Id;
            newAffiliation.FS_Primary_Affiliation__c = true;
            
            insert newAffiliation;
            result.put('Success', true);
        } catch (Exception e) {
            System.debug(e.getStackTraceString());
            System.debug(e.getLineNumber());
            System.debug(e.getMessage());
            System.debug(e.getCause());
            result.put('Error', e.getMessage() + '; ' + e.getStackTraceString() + '; ' + e.getLineNumber() + '; ' + e.getCause());
            Database.rollback(sp);
        }
        return result;
    }

    private static List<Map<String, Object>> getFieldSets(String objectName, String fieldSetAPI) {
        Schema.SObjectType objectType = Schema.getGlobalDescribe().get(objectName);
        Schema.DescribeSObjectResult objectDescribe = objectType.getDescribe();
        Map<String, Schema.FieldSet> fieldSetMap = objectDescribe.fieldSets.getMap();
        Schema.FieldSet fieldSet = fieldSetMap.get(fieldSetAPI);
        List<Schema.FieldSetMember> fieldSetMembers = fieldSet.getFields();

        pickListFields = new Set<String>();

        List<Map<String, Object>> fieldSetsList = new List<Map<String, Object>>();
        for (Schema.FieldSetMember tempFieldSetMember : fieldSetMembers) {
            String type = String.valueOf(tempFieldSetMember.getType()).toLowerCase();
            if (type == 'string') {
                type = 'text';
            }
            if (type == 'phone') {
                type = 'tel';
            }
            if (type == 'double') {
                type = 'number';
            }
            if (type == 'picklist') {
                pickListFields.add(tempFieldSetMember.fieldPath);
            }
            if (type == 'reference') {
                type = 'lookup';
            }
            Map<String, Object> tempMap;

            String tempLabel;
            switch on tempFieldSetMember.fieldPath {
                when 'OrderApi__Personal_Email__c' {
                    tempLabel = 'Email';
                }
                when 'OrderApi__Work_Email__c' {
                    tempLabel = 'Email';
                }
                when 'OrderApi__Other_Email__c' {
                    tempLabel = 'Email';
                }
                when else {
                    tempLabel = tempFieldSetMember.label;
                }
            }

            if (type == 'checkbox') {
                tempMap = new Map<String, Object>{
                        'APIName' => tempFieldSetMember.fieldPath,
                        'Label' => tempLabel,
                        'Required' => tempFieldSetMember.required,
                        'DBRequired' => tempFieldSetMember.DBRequired,
                        'Type' => type,
                        'Value' => false
                };
            } else {
                tempMap = new Map<String, Object>{
                        'APIName' => tempFieldSetMember.fieldPath,
                        'Label' => tempLabel,
                        'Required' => tempFieldSetMember.required,
                        'DBRequired' => tempFieldSetMember.DBRequired,
                        'Type' => type,
                        'Value' => ''
                };
            }
            fieldSetsList.add(tempMap);
        }
        return fieldSetsList;
    }

    private static List<Map<String, String>> getPicklistOptions(String objectName, String fieldAPI) {
        List<Map<String, String>> options = new List<Map<String, String>>();
        Schema.DescribeFieldResult fieldResult = Schema.describeSObjects(new List<String>{objectName})[0].fields.getMap().get(fieldAPI).getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

        for (Schema.PicklistEntry f : ple) {
            options.add(new Map<String, String>{
                    'label' => f.getLabel(), 'value' => f.getValue()
            });
        }
        return options;
    }

    private class MyPickListInfo {
        public String validFor;
    }

    private static Map<String, Object> getDependentPicklist(String objectName, String controllingField, String dependentField) {
        Map<String, List<Map<String, String>>> dependentMap = new Map<String, List<Map<String, String>>>();
        List<Map<String, String>> controllingList = new List<Map<String, String>>();

        if (objectName.equals('User') && controllingField.equals('countrycode') && dependentField.equals('statecode')) {
            controllingList.add(new Map<String, String>{'value' => 'US', 'label' => 'United States'});
            controllingList.add(new Map<String, String>{'value' => 'CA', 'label' => 'Canada'});
        }

        Map<String, SObjectField> tempDescribeSObjectResult = Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap();

        Schema.DescribeFieldResult controllingFieldInfo = tempDescribeSObjectResult.get(controllingField).getDescribe();
        Schema.DescribeFieldResult dependentFieldInfo = tempDescribeSObjectResult.get(dependentField).getDescribe();

        List<Schema.PicklistEntry> controllingValues = controllingFieldInfo.getPicklistValues();
        List<Schema.PicklistEntry> dependentValues = dependentFieldInfo.getPicklistValues();

        for (Schema.PicklistEntry currControllingValue : controllingValues) {
            dependentMap.put(currControllingValue.getValue(), new List<Map<String, String>>());
            if (objectName.equals('User') && controllingField.equals('countrycode') && dependentField.equals('statecode')) {
                if (!currControllingValue.getValue().equals('US') && !currControllingValue.getValue().equals('CA')) {
                    controllingList.add(new Map<String, String>{
                            'value' => currControllingValue.getValue(), 'label' => currControllingValue.getLabel()
                    });
                }
            } else {
                controllingList.add(new Map<String, String>{
                        'value' => currControllingValue.getValue(), 'label' => currControllingValue.getLabel()
                });
            }
        }

        for (Schema.PicklistEntry currDependentValue : dependentValues) {
            String jsonString = JSON.serialize(currDependentValue);
            MyPickListInfo info = (MyPickListInfo) JSON.deserialize(jsonString, MyPickListInfo.class);
            String hexString = EncodingUtil.convertToHex(EncodingUtil.base64Decode(info.validFor)).toUpperCase();
            Integer baseCount = 0;

            Map<String, String> temp = new Map<String, String>();
            temp.put('label', currDependentValue.getLabel());
            temp.put('value', currDependentValue.getValue());

            for (Integer curr : hexString.getChars()) {
                Integer val = 0;
                if (curr >= 65) {
                    val = curr - 65 + 10;
                } else {
                    val = curr - 48;
                }

                if ((val & 8) == 8) {
                    dependentMap.get(controllingValues[baseCount + 0].getValue()).add(temp);
                }
                if ((val & 4) == 4) {
                    dependentMap.get(controllingValues[baseCount + 1].getValue()).add(temp);
                }
                if ((val & 2) == 2) {
                    dependentMap.get(controllingValues[baseCount + 2].getValue()).add(temp);
                }
                if ((val & 1) == 1) {
                    dependentMap.get(controllingValues[baseCount + 3].getValue()).add(temp);
                }

                baseCount += 4;
            }
        }
        Map<String, Object> result = new Map<String, Object>();
        result.put('controllingList', controllingList);
        result.put('dependentMap', dependentMap);
        return result;
    }
}