unpackaged/main/default/objects/FS_Affiliation__c/FS_Affiliation__c.object-meta.xml
<CustomObject>
    <description>An Affiliation links Accounts and Contacts. It defines relationships between companies and employees, relationships amongst employees etc</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>Affiliation {0000000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FS_Affiliation__c/fields/FS_Child_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Child_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contact affiliated to the company account</inlineHelpText>
    <label>Child Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parent Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FS_AffiliationsTest.cls
@Istest
public class FS_AffiliationsTest {
	@TestSetup
    private static void install() {
        Framework.Installer.install();
        PagesApi.PackageScripts.install();
        OrderApi.PackageScripts.install();
        
        Framework.RoutingRule[] rules = new List<Framework.RoutingRule>();
        Framework.RoutingRule FS_AffiliationsRule = new Framework.RoutingRule();
        FS_AffiliationsRule.apexClass = FS_Affiliations.class.getName();
        FS_AffiliationsRule.namespace = '';
        FS_AffiliationsRule.isEnabled = true;
        FS_AffiliationsRule.sObjectName = 'FS_Affiliation__c';
        FS_AffiliationsRule.executionOrder = 10;
        rules.add(FS_AffiliationsRule);
        Framework.Config.push(rules);
    }
    
    @istest
    static void affiliationsTestInsert(){
        Contact con =new Contact();
        con.LastName = 'Test Contact';
        insert con;
        
        FS_Affiliation__c affiliations = new FS_Affiliation__c();
        affiliations.FS_Child_Contact__c = con.Id;
        insert affiliations;
        List<FS_Affiliation__c> affiliationList = [SELECT Id FROM FS_Affiliation__c WHERE Id=:affiliations.Id];
        FS_Affiliations FSAffiliationsRoutingRule = new FS_Affiliations(affiliationList);
        FS_Affiliations.Constructor cons = new FS_Affiliations.Constructor();
        cons.construct(affiliationList);
        Framework.Dispatcher.dispatchTrigger();
    }
    
}