unpackaged/main/default/objects/FS_Order_Fulfillment__c/FS_Order_Fulfillment__c.object-meta.xml
<CustomObject>
    <description>Custom object to track order fulfillments for shippable items</description>
    <label>Order Fulfillment</label>
    <nameField>
        <displayFormat>OF {000000}</displayFormat>
        <label>OF ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders Fulfillment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FS_Order_Fulfillment__c/fields/FS_Order_Tracking__c.field-meta.xml
<CustomField>
    <fullName>FS_Order_Tracking__c</fullName>
    <inlineHelpText>Order Tracking record tied to the fulfillment record</inlineHelpText>
    <label>Order Tracking</label>
    <referenceTo>FS_Order_Tracking__c</referenceTo>
    <relationshipLabel>Orders Fulfillment</relationshipLabel>
    <relationshipName>Orders_Fulfillment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/FS_Order_Tracking__c/FS_Order_Tracking__c.object-meta.xml
<CustomObject>
    <description>Custom field to track shipment information tied to the Sales Order</description>
    <label>Order Tracking</label>
    <nameField>
        <displayFormat>OT {000000}</displayFormat>
        <label>Order Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/FS_Order_FulfillmentsTest.cls
@Istest
public class FS_Order_FulfillmentsTest {
    
    @TestSetup
    private static void install() {
        Framework.Installer.install();
        PagesApi.PackageScripts.install();
        OrderApi.PackageScripts.install();
        
        Framework.RoutingRule[] rules = new List<Framework.RoutingRule>();
        Framework.RoutingRule FS_Order_FulfillmentsRule = new Framework.RoutingRule();
        FS_Order_FulfillmentsRule.apexClass = FS_Order_Fulfillments.class.getName();
        FS_Order_FulfillmentsRule.namespace = '';
        FS_Order_FulfillmentsRule.isEnabled = true;
        FS_Order_FulfillmentsRule.sObjectName = 'FS_Order_Fulfillment__c';
        FS_Order_FulfillmentsRule.executionOrder = 10;
        rules.add(FS_Order_FulfillmentsRule);
        Framework.Config.push(rules);
    }
    
    @istest
    private static void FS_Order_FulfillmentsTestInsert(){
        //inserting orderTracking
        FS_Order_Tracking__c order=new FS_Order_Tracking__c();
        insert order;
        
        //inserting order fullfillmentList
        List<FS_Order_Fulfillment__c> orderList=new List<FS_Order_Fulfillment__c>();
        FS_Order_Fulfillment__c orderFullfill=new FS_Order_Fulfillment__c(FS_Order_Tracking__c=order.Id);
        orderList.add(orderFullfill);
        insert orderList;
        
        FS_Order_Fulfillments sRule=new FS_Order_Fulfillments(orderList);
        FS_Order_Fulfillments.Constructor fscc=new FS_Order_Fulfillments.Constructor();
        fscc.construct(orderList);
        
    }
}