unpackaged/main/default/objects/FS_Order_Fulfillment__c/FS_Order_Fulfillment__c.object-meta.xml
<CustomObject>
    <description>Custom object to track order fulfillments for shippable items</description>
    <label>Order Fulfillment</label>
    <nameField>
        <displayFormat>OF {000000}</displayFormat>
        <label>OF ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders Fulfillment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FS_Order_Fulfillment__c/fields/FS_Order__c.field-meta.xml
<CustomField>
    <fullName>FS_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipLabel>Orders Fulfillment</relationshipLabel>
    <relationshipName>Orders_Fulfillment</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FS_Order_Fulfillment__c/fields/FS_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>FS_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line</label>
    <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
    <relationshipLabel>Orders Fulfillment</relationshipLabel>
    <relationshipName>Orders_Fulfillment</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FS_Order_Fulfillment__c/fields/FS_Order_Tracking__c.field-meta.xml
<CustomField>
    <fullName>FS_Order_Tracking__c</fullName>
    <inlineHelpText>Order Tracking record tied to the fulfillment record</inlineHelpText>
    <label>Order Tracking</label>
    <referenceTo>FS_Order_Tracking__c</referenceTo>
    <relationshipLabel>Orders Fulfillment</relationshipLabel>
    <relationshipName>Orders_Fulfillment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/FS_Order_Fulfillment__c/fields/FS_Quantity_Shipped__c.field-meta.xml
<CustomField>
    <fullName>FS_Quantity_Shipped__c</fullName>
    <inlineHelpText>Quantity of items shipped</inlineHelpText>
    <label>Quantity Shipped</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/FS_Order_Tracking__c/FS_Order_Tracking__c.object-meta.xml
<CustomObject>
    <description>Custom field to track shipment information tied to the Sales Order</description>
    <label>Order Tracking</label>
    <nameField>
        <displayFormat>OT {000000}</displayFormat>
        <label>Order Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FS_Order_Tracking__c/fields/FS_Quantity__c.field-meta.xml
<CustomField>
    <fullName>FS_Quantity__c</fullName>
    <inlineHelpText>Quantity of items in sales order line shipped</inlineHelpText>
    <label>Quantity</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/FS_Order_Tracking__c/fields/FS_Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>FS_Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Sales Order tied to the shippable items</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipLabel>Orders Tracking</relationshipLabel>
    <relationshipName>FS_Orders_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FS_Order_Tracking__c/fields/FS_Sales_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>FS_Sales_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OrderApi__Sales_Order_Line__c.OrderApi__Sales_Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Sales_Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
    <relationshipLabel>Orders Tracking</relationshipLabel>
    <relationshipName>Orders_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FS_AutoPopulateOrderDetailsTest.cls
/**
 * Created by cloudwebsolutions on 13-01-2020.
 */

@IsTest
private class FS_AutoPopulateOrderDetailsTest {

    private static final Integer QUANTITY = 3;

    @TestSetup
    private static void install() {

        Framework.Installer.install();
        PagesApi.PackageScripts.install();
        OrderApi.PackageScripts.install();
        EventApi.PackageScripts.install();

        Framework.RoutingRule[] rules = new List<Framework.RoutingRule>();
        Framework.RoutingRule populateOrderFields = new Framework.RoutingRule();
        populateOrderFields.apexClass = FS_AutoPopulateOrderDetails.class.getName();
        populateOrderFields.namespace = '';
        populateOrderFields.isEnabled = true;
        populateOrderFields.sObjectName = 'FS_Order_Fulfillment__c';
        populateOrderFields.executionOrder = 30;
        rules.add(populateOrderFields);
        Framework.Config.push(rules);

        Account account = FS_TestUtils.createAccount('TestAadasd21sccount123asd');
        insert account;

        //Insert contact
        Contact contact = FS_TestUtils.createContact('TestConsdqfq23asdtact', 'te123stdasd12@gmail.com');
        insert contact;
    }

    @IsTest
    static void testBehavior() {

        //Insert account
        Account account = [SELECT Id FROM Account WHERE Name='TestAadasd21sccount123asd'][0];


        //Insert contact
        Contact contact = [SELECT Id FROM Contact WHERE LastName = 'TestConsdqfq23asdtact'][0];

        //Insert SalesOrder
        OrderApi__Sales_Order__c salesOrder = FS_TestUtils.createSalesOrder(contact.id, account.id, 'Receipt', 'Open');
        insert salesOrder;

        //Insert ItemClass
        OrderApi__Item_Class__c itemClass = FS_TestUtils.createItemClass('Test');
        insert itemClass;

        //Insert Item
        OrderApi__Item__c item = FS_TestUtils.createItem('TestItem', itemClass.id);
        insert item;

        //Insert SalesOrderLine
        OrderApi__Sales_Order_Line__c salesOrderLine = FS_TestUtils.createSalesOrderLine(item.id, salesOrder.id, contact.id, account.id);
        insert salesOrderLine;
        salesOrder.OrderApi__Status__c = 'posted';
        update salesOrder;

        //Insert OrderTracking
        List<FS_Order_Tracking__c> orderTrackings = new List<FS_Order_Tracking__c>();
        FS_Order_Tracking__c orderTracking = new FS_Order_Tracking__c();
        orderTracking.FS_Quantity__c = String.valueOf(QUANTITY);
        orderTracking.FS_Sales_Order_Line__c = salesOrderLine.id;
        orderTracking.FS_Sales_Order__c = salesOrder.id;
        orderTrackings.add(orderTracking);
        insert orderTrackings;

        //Insert OrderFulfillment
        List<FS_Order_Fulfillment__c> fulfillments = new List<FS_Order_Fulfillment__c>();
        FS_Order_Fulfillment__c orderFulfillment = new FS_Order_Fulfillment__c();
        orderFulfillment.FS_Order_Tracking__c = orderTrackings[0].id;
        orderFulfillment.FS_Quantity_Shipped__c = QUANTITY;
        orderFulfillment.FS_Order__c = salesOrder.id;
        orderFulfillment.FS_Order_Line__c = salesOrderLine.id;
        fulfillments.add(orderFulfillment);
        insert fulfillments;

        Test.startTest();
        FS_AutoPopulateOrderDetails programGoalsRoutingRule = new FS_AutoPopulateOrderDetails(fulfillments);
        FS_AutoPopulateOrderDetails.Constructor fscc = new FS_AutoPopulateOrderDetails.Constructor();
        fscc.construct(fulfillments);
        programGoalsRoutingRule.beforeInsert();
        Test.stopTest();
    }
}