unpackaged/main/default/objects/FS_Order_Fulfillment__c/FS_Order_Fulfillment__c.object-meta.xml
<CustomObject>
    <description>Custom object to track order fulfillments for shippable items</description>
    <label>Order Fulfillment</label>
    <nameField>
        <displayFormat>OF {000000}</displayFormat>
        <label>OF ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders Fulfillment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FS_Order_Fulfillment__c/fields/FS_Order__c.field-meta.xml
<CustomField>
    <fullName>FS_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipLabel>Orders Fulfillment</relationshipLabel>
    <relationshipName>Orders_Fulfillment</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FS_Order_Fulfillment__c/fields/FS_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>FS_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line</label>
    <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
    <relationshipLabel>Orders Fulfillment</relationshipLabel>
    <relationshipName>Orders_Fulfillment</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FS_Order_Fulfillment__c/fields/FS_Order_Tracking__c.field-meta.xml
<CustomField>
    <fullName>FS_Order_Tracking__c</fullName>
    <inlineHelpText>Order Tracking record tied to the fulfillment record</inlineHelpText>
    <label>Order Tracking</label>
    <referenceTo>FS_Order_Tracking__c</referenceTo>
    <relationshipLabel>Orders Fulfillment</relationshipLabel>
    <relationshipName>Orders_Fulfillment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/FS_Order_Tracking__c/FS_Order_Tracking__c.object-meta.xml
<CustomObject>
    <description>Custom field to track shipment information tied to the Sales Order</description>
    <label>Order Tracking</label>
    <nameField>
        <displayFormat>OT {000000}</displayFormat>
        <label>Order Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FS_Order_Tracking__c/fields/FS_Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>FS_Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Sales Order tied to the shippable items</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipLabel>Orders Tracking</relationshipLabel>
    <relationshipName>FS_Orders_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FS_Order_Tracking__c/fields/FS_Sales_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>FS_Sales_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OrderApi__Sales_Order_Line__c.OrderApi__Sales_Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Sales_Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
    <relationshipLabel>Orders Tracking</relationshipLabel>
    <relationshipName>Orders_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FS_AutoPopulateOrderDetails.cls
/**
 * Created by cloudwebsolutions on 13-01-2020.
 */

global without sharing class FS_AutoPopulateOrderDetails extends Framework.Domain {
    public FS_AutoPopulateOrderDetails(List<FS_Order_Fulfillment__c > sObjectList) {
        super(sObjectList);
    }

    global class Constructor implements Framework.Domain.DomainConstructor {
        global Framework.Domain construct(List<SObject> sObjectList) {
            return new FS_AutoPopulateOrderDetails(sObjectList);
        }
    }

    public override void beforeInsert() {
        Framework.Log.push(FS_AutoPopulateOrderDetails.class.getName(), 'Before Insert');
        populateOrderAndOrderLineIds((FS_Order_Fulfillment__c[]) records);
        Framework.Log.pop();
    }

    private static void populateOrderAndOrderLineIds(List<FS_Order_Fulfillment__c> fulfillments) {
        Set<Id> orderTrackingIds = new Set<Id>();

        //Storing the orderTracking ids into a set
        for (FS_Order_Fulfillment__c fulfillment : fulfillments) {
            orderTrackingIds.add(fulfillment.FS_Order_Tracking__c);
        }

        //Retrieving the orderTracking record associated with the orderfulfillments.
        Map<Id, FS_Order_Tracking__c> orderTrackingMap = new Map<Id, FS_Order_Tracking__c>([
                SELECT FS_Sales_Order__c,FS_Sales_Order_Line__c
                FROM FS_Order_Tracking__c
                WHERE Id IN:orderTrackingIds
                AND FS_Sales_Order__c != NULL
        ]);


        //Updating the salesOrder and salesOrderline ids to the fulfillment record
        if (orderTrackingMap != NULL && !orderTrackingMap.isEmpty()) {
            for (FS_Order_Fulfillment__c fulfillment : fulfillments) {
                if (orderTrackingMap.containsKey(fulfillment.FS_Order_Tracking__c)) {
                    fulfillment.FS_Order__c = orderTrackingMap.get(fulfillment.FS_Order_Tracking__c).FS_Sales_Order__c;
                    fulfillment.FS_Order_Line__c = orderTrackingMap.get(fulfillment.FS_Order_Tracking__c).FS_Sales_Order_Line__c;
                }
            }
        }
    }
}