unpackaged/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <description>Used to log errors from integration</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Integration_Log__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint of the external system/application</description>
    <label>Endpoint</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Error message from the webservice callout</description>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <description>Will hold description of the type of integration job</description>
    <label>Job</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <description>Body of the callout request</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Request_Header__c.field-meta.xml
<CustomField>
    <fullName>Request_Header__c</fullName>
    <description>Request header from the callout</description>
    <label>Request Header</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <description>Body of the response received/sent to/from external system/application</description>
    <label>Response Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Response_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Code__c</fullName>
    <description>Code returned OR sent to the external system/application after processing request</description>
    <label>Response Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Salesforce_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Record_ID__c</fullName>
    <description>Id of the Salesforce record off of which the integration was triggered</description>
    <label>Salesforce Record ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Success__c.field-meta.xml
<CustomField>
    <fullName>Success__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to determine if the callout was successful or not</description>
    <label>Success</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/Plative_IntegrationLogTest.cls
/**
 * Company     : Plative
 * Description : 
 * ****************************************************************************************
 * Test class for Integration log classes
 * ****************************************************************************************
 * History     : 
 * [13.Aug.2019] Anisa Shaikh - Code Creation 
*/
@isTest
private class Plative_IntegrationLogTest {

    static testMethod void testWrapperClass() {
        test.startTest();

            Plative_IntegrationLog log1 = new Plative_IntegrationLog();     
            log1.endpoint = '';
            log1.job= '';
            log1.reqHeader = '';
            log1.reqBody = '';
            log1.respCode = '';
            log1.respBody = '';
            log1.errMsg = '';
            log1.success= false;
			log1.relatedRecordId = '';
            Plative_IntegrationLog log2 = new Plative_IntegrationLog('', '', '', '', '', '', '', false,'');        
        test.stopTest();
    }

    static testMethod void testController() {
            Integration_Log__c logObject = new Integration_Log__c();
            logObject.Endpoint__c= '';
            logObject.Job__c= 'TEST';
            logObject.Request_Header__c='';
            logObject.Request_Body__c='';
            logObject.Response_Code__c='';
            logObject.Response_Body__c='';
            logObject.Error_Message__c='';
            logObject.Success__c =false;
			logObject.Salesforce_Record_ID__c = 'test';         
            insert logObject;
			Test.startTest();
				List<Integration_Log__c> lstLogs = Plative_RelatedLogsController.queryLogRecords('test');
            Test.stopTest();
			System.assertEquals(1, lstLogs.size());
    }

	static testMethod void testPurging() {

            Integration_Log__c logObject = new Integration_Log__c();
            logObject.Endpoint__c= '';
            logObject.Job__c= 'TEST';
            logObject.Request_Header__c='';
            logObject.Request_Body__c='';
            logObject.Response_Code__c='';
            logObject.Response_Body__c='';
            logObject.Error_Message__c='';
            logObject.Success__c =false;
			logObject.Salesforce_Record_ID__c = 'test';         
            insert logObject;
			Test.startTest();
				Plative_PurgeLogsSchedulable purgeLogs = new Plative_PurgeLogsSchedulable();
				purgeLogs.execute(null);
            Test.stopTest();


	}
}