unpackaged/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <description>Used to log errors from integration</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Integration_Log__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint of the external system/application</description>
    <label>Endpoint</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Error message from the webservice callout</description>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <description>Will hold description of the type of integration job</description>
    <label>Job</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <description>Body of the callout request</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Request_Header__c.field-meta.xml
<CustomField>
    <fullName>Request_Header__c</fullName>
    <description>Request header from the callout</description>
    <label>Request Header</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <description>Body of the response received/sent to/from external system/application</description>
    <label>Response Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Response_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Code__c</fullName>
    <description>Code returned OR sent to the external system/application after processing request</description>
    <label>Response Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Salesforce_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Record_ID__c</fullName>
    <description>Id of the Salesforce record off of which the integration was triggered</description>
    <label>Salesforce Record ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Success__c.field-meta.xml
<CustomField>
    <fullName>Success__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to determine if the callout was successful or not</description>
    <label>Success</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/Plative_IntegrationLog.cls
/**
 * Company     : Plative
 * Description : 
 * ****************************************************************************************
 * Generic log class to create integration log object records.
 * ****************************************************************************************
 * History     : 
 * [05.Aug.2019] Anisa Shaikh - Code Creation 
**/
public class Plative_IntegrationLog  {
    
    public Integration_Log__c logObject;
    public String endPoint{get;set;}
    public String job{get;set;}
    public String reqHeader{get;set;}
    public String reqBody{get;set;}
    public String respCode{get;set;}
    public String respBody{get;set;}
    public String errMsg{get;set;}
    public Boolean success{get;set;}
	public String relatedRecordId{get;set;}
	   
    public Integration_Log__c getlogObject(){
        return this.logObject;
    }


    /**
     * Company     : Plative Company
     * ****************************************************************************************
     * Default constructor
     * ****************************************************************************************
    **/
    public Plative_IntegrationLog(){

    }

    /**
     * Company     : Plative Company
     * ****************************************************************************************
     * Parameterized constructor
     * ****************************************************************************************
    **/
    public Plative_IntegrationLog(String endPoint, String job, String reqHeader, String reqBody,
                              String respCode, String respBody, String errMsg, boolean success,
							  String relatedRecordId){
        this.logObject = new Integration_Log__c();
        this.logObject.Endpoint__c= endPoint;
        this.logObject.Job__c= job;
        this.logObject.Request_Header__c=reqHeader;
        this.logObject.Request_Body__c=reqBody;
        this.logObject.Response_Code__c=respCode;
        this.logObject.Response_Body__c=respBody;
        this.logObject.Error_Message__c=errMsg;
        this.logObject.Success__c =success;
		this.logObject.Salesforce_Record_ID__c = relatedRecordId;
    }

}