unpackaged/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <description>Used to log errors from integration</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Log_Setting__mdt/Log_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This mdt will hold settings for integration log framework</description>
    <label>Log Setting</label>
    <pluralLabel>Log Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Log_Setting__mdt/fields/Maximum_log_age__c.field-meta.xml
<CustomField>
    <fullName>Maximum_log_age__c</fullName>
    <description>Maximum number of days for which log records are to be retained in the system.</description>
    <label>Maximum log age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/Plative_PurgeLogsSchedulable.cls
/**
 * Company     : Plative
 * Description : 
 * ****************************************************************************************
 * Schedulable class to delete old log records in the system
 * ****************************************************************************************
 * History     : 
 * [05.Aug.2019] Anisa Shaikh - Code Creation 
**/
global class Plative_PurgeLogsSchedulable implements Schedulable {
    /**
     * @description Deleted older log records
     * @param sc contains the job ID
     */ 
    global void execute(SchedulableContext sc) {
        List<Log_Setting__mdt> logSettings;
        try{
            logSettings = [SELECT Maximum_log_age__c FROM  Log_Setting__mdt];
        }
        catch(Exception e){
            System.debug('EXCEPTION '+e.getMessage()+e.getStackTraceString());
        }

        Decimal logAge = 365;
        if(logSettings != null && !logSettings.isEmpty()){
            logAge = logSettings[0].Maximum_log_age__c;
        }
        try{
            String soql = 'SELECT Id FROM Integration_Log__c WHERE CreatedDate < LAST_N_DAYS:'+logAge;
            List<Integration_Log__c> lstLogs = Database.query(soql);
            if(lstLogs != null && !lstLogs.isEmpty()){
                delete lstLogs;
            }
        }
        catch(Exception e){
            System.debug('EXCEPTION '+e.getMessage()+e.getStackTraceString());
        }
    }
}