unpackaged/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <description>Used to log errors from integration</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Integration_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Error message from the webservice callout</description>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <description>Will hold description of the type of integration job</description>
    <label>Job</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Response_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Code__c</fullName>
    <description>Code returned OR sent to the external system/application after processing request</description>
    <label>Response Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Salesforce_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Record_ID__c</fullName>
    <description>Id of the Salesforce record off of which the integration was triggered</description>
    <label>Salesforce Record ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Success__c.field-meta.xml
<CustomField>
    <fullName>Success__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to determine if the callout was successful or not</description>
    <label>Success</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/Plative_RelatedLogsController.cls
/**
* Company     : Plative
* Description : Controller to the Plative_RelatedLogs lightning component
* [07.Dec.2020] Plative - Code Creation
*/
public class Plative_RelatedLogsController  {

	/*
	* Description : Query all Integration Log records for the given record
	*/
	@AuraEnabled
	public static List<Integration_Log__c> queryLogRecords(String relatedRecordId){
		
		List<Integration_Log__c> lstLogRecords = new List<Integration_Log__c>();
		try{
			lstLogRecords = [SELECT Id,Name,Job__c,Success__c,Error_Message__c, Response_Code__c,CreatedDate 
							 FROM Integration_Log__c 
							 WHERE Salesforce_Record_ID__c =:relatedRecordId 
							 ORDER BY CreatedDate DESC
							 LIMIT 10];

		}
		catch(Exception	e){
			System.debug('EXCEPTION'+e.getMessage()+e.getStackTraceString());
			return null;
		}
		return lstLogRecords;
	}

}