unpackaged/main/default/objects/Logistics__c/Logistics__c.object-meta.xml
<CustomObject>
    <description>Object to track all event related logistics</description>
    <label>Logistic</label>
    <nameField>
        <displayFormat>L{000000}</displayFormat>
        <label>Logistics ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logistics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Logistics__c/fields/FS_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Type__c</fullName>
    <inlineHelpText>Type of logistic</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Laptops</fullName>
            </value>
            <value>
                <fullName>Monitors</fullName>
            </value>
            <value>
                <fullName>Booths</fullName>
            </value>
            <value>
                <fullName>Microphone</fullName>
            </value>
            <value>
                <fullName>Notepads</fullName>
            </value>
            <value>
                <fullName>Pens</fullName>
            </value>
            <value>
                <fullName>Projector</fullName>
            </value>
            <value>
                <fullName>Recording Equipment</fullName>
            </value>
            <value>
                <fullName>Tabletop</fullName>
            </value>
            <value>
                <fullName>Chairs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/FS_LogisticsTest.cls
@IsTest
public class FS_LogisticsTest {
	@TestSetup
      private static void install() {
          Framework.Installer.install();
          PagesApi.PackageScripts.install();
          OrderApi.PackageScripts.install();

          Framework.RoutingRule[] rules = new List<Framework.RoutingRule>();
          Framework.RoutingRule FS_LogisticsRule = new Framework.RoutingRule();
          FS_LogisticsRule.apexClass = FS_Logistics.class.getName();
          FS_LogisticsRule.namespace = '';
          FS_LogisticsRule.isEnabled = true;
          FS_LogisticsRule.sObjectName = 'Logistics__c';
          FS_LogisticsRule.executionOrder = 11;
          rules.add(FS_LogisticsRule);
          Framework.Config.push(rules);
      }
    @Istest
    static void logisticsTestInsert(){
        List<Logistics__c> logisticsList = new List<Logistics__c>();
    	Logistics__c logistics = new Logistics__c(
			FS_Type__c='Microphone');
        logisticsList.add(logistics);
        insert logisticsList;
        FS_Logistics FS_LogisticsRule = new FS_Logistics(logisticsList);
        FS_Logistics.Constructor logi = new FS_Logistics.Constructor();
        logi.construct(logisticsList);
        Framework.Dispatcher.dispatchTrigger();
    }
          

}