unpackaged/main/default/objects/Contact/fields/FS_Contact_Member_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Contact_Member_Status__c</fullName>
    <formula>IF (ISBLANK(FS_Membership_Expiry_Date__c ), "",
IF(FS_Membership_Days_to_Expire__c   &gt; 0,'Active',
IF(FS_Membership_Days_to_Expire__c   &gt;= -90, 'Grace',
IF(FS_Membership_Days_to_Expire__c &lt; -90, 'Expired',
'Non-Member'
))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Member Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FS_Member_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Member_Status__c</fullName>
    <label>Member Status DO NOT USE</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FS_Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Membership_Expiry_Date__c</fullName>
    <inlineHelpText>Expiry date of membership</inlineHelpText>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/FS_Community_Group_Member_Term__c/FS_Community_Group_Member_Term__c.object-meta.xml
<CustomObject>
    <label>Community Group Member Term</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Community Group Member Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Group Member Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FS_Community_Group_Member_Term__c/fields/FS_Community_Group_Member__c.field-meta.xml
<CustomField>
    <fullName>FS_Community_Group_Member__c</fullName>
    <label>Community Group Member</label>
    <referenceTo>PagesApi__Community_Group_Member__c</referenceTo>
    <relationshipLabel>Community Group Member Terms</relationshipLabel>
    <relationshipName>Community_Group_Member_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/FS_Community_Group_Member_Term__c/fields/FS_Deactivated_Manually__c.field-meta.xml
<CustomField>
    <fullName>FS_Deactivated_Manually__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivated Manually</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/FS_Community_Group_Member_Term__c/fields/FS_Term_End_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Term_End_Date__c</fullName>
    <description>The end date for community group member term</description>
    <inlineHelpText>The end date for community group member term</inlineHelpText>
    <label>Term End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/FS_Community_Group_Member_Term__c/fields/FS_Term_Grace_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Term_Grace_Period_End_Date__c</fullName>
    <inlineHelpText>Grace Period End Date is based off the related Subscription Term's Grace Period End Date</inlineHelpText>
    <label>Term Grace Period End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/FS_Community_Group_Member_Term__c/fields/FS_Term_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Term_Start_Date__c</fullName>
    <description>The start date for community group member term</description>
    <inlineHelpText>The start date for community group member term</inlineHelpText>
    <label>Term Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/FS_CommunityGroupMemberDropTest.cls
/**
 * Created by cmudd on 2019-10-17.
 */
@IsTest
public without sharing class FS_CommunityGroupMemberDropTest {
    @TestSetup
    public static void install() {
        Framework.Installer.install();
        PagesApi.PackageScripts.install();
        OrderApi.PackageScripts.install();
        EventApi.PackageScripts.install();
        ROEApi.PackageScripts.install();
        CPBase.PackageScripts.install();
        LTE.PackageScripts.install();
        FDService.BUPackageScripts.install();
        DonorApi.PackageScripts.install();
        JoinApi.PackageScripts.install();
        ProgramApi.PackageScripts.install();
        PriceApi.PackageScripts.install();
        DRCTS.PackageScripts.install();

        Framework.RoutingRule[] rules = new List<Framework.RoutingRule>();
        Framework.RoutingRule routingRule= new Framework.RoutingRule();
        routingRule.apexClass = FS_CommunityGroupMemberDrop.class.getName();
        routingRule.namespace = ' ';
        routingRule.isEnabled = true;
        routingRule.sObjectName = 'Contact';
        routingRule.executionOrder = 10;
        rules.add(routingRule);
        Framework.Config.push(rules);
    }

    @IsTest
    private static void testDroppingMembership_ExpectCommMembersDeactivated() {
        List<Contact> conList = new List<Contact>();
        Contact con = new Contact(FirstName='Test',LastName='Fusionspan', FS_Membership_Expiry_Date__c = System.today()+5,FS_Member_Status__c='Active');
        conList.add(con);
        insert conList;

        PagesApi__Community_Group__c communityGroup=new PagesApi__Community_Group__c(Name='Test Group');
        insert communityGroup;

        PagesApi__Community_Group_Member__c communityGroupMember = new PagesApi__Community_Group_Member__c(PagesApi__Contact__c=con.Id,
                PagesApi__Is_Active__c=true,FS_Grace_Period_End_Date__c=null,FS_Paid_Through_Date__c=System.today().addDays(5),PagesApi__Community_Group__c=communityGroup.Id);
        insert communityGroupMember;

        FS_Community_Group_Member_Term__c communityGroupMemberTerm = new FS_Community_Group_Member_Term__c(FS_Term_Start_Date__c=System.today().addYears(-1),FS_Term_End_Date__c=System.today().addDays(5),
                FS_Term_Grace_Period_End_Date__c=null,FS_Deactivated_Manually__c=false,FS_Community_Group_Member__c=communityGroupMember.Id);
        insert communityGroupMemberTerm;

        Test.startTest();
        con.FS_Member_Status__c = 'Inactive';
        update con;
        Test.stopTest();

        communityGroupMember.PagesApi__Is_Active__c = false;
        communityGroupMember.FS_Paid_Through_Date__c = System.today();
        update communityGroupMember;

        communityGroupMemberTerm.FS_Deactivated_Manually__c=true;
        communityGroupMemberTerm.FS_Term_End_Date__c=System.today();
        update communityGroupMemberTerm;

//        Map<Id,Contact> contactMapMap = new Map<Id,Contact>([SELECT Id,FS_Contact_Member_Status__c FROM Contact WHERE Id=:conList]);

        System.assertEquals(0, [SELECT Id FROM PagesApi__Community_Group_Member__c WHERE PagesApi__Is_Active__c = TRUE].size());

//        FS_CommunityGroupMemberDrop cGroupMemDrop = new FS_CommunityGroupMemberDrop(conList);
//        FS_CommunityGroupMemberDrop.Constructor constructor = new FS_CommunityGroupMemberDrop.Constructor();
//        constructor.construct(conList);
//        cGroupMemDrop.afterUpdate(contactMapMap);
    }
}