unpackaged/main/default/objects/Contact/fields/FS_Contact_Member_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Contact_Member_Status__c</fullName>
    <formula>IF (ISBLANK(FS_Membership_Expiry_Date__c ), "",
IF(FS_Membership_Days_to_Expire__c   &gt; 0,'Active',
IF(FS_Membership_Days_to_Expire__c   &gt;= -90, 'Grace',
IF(FS_Membership_Days_to_Expire__c &lt; -90, 'Expired',
'Non-Member'
))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Member Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FS_Member_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Member_Status__c</fullName>
    <label>Member Status DO NOT USE</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/FS_Community_Group_Member_Term__c/FS_Community_Group_Member_Term__c.object-meta.xml
<CustomObject>
    <label>Community Group Member Term</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Community Group Member Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Group Member Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FS_Community_Group_Member_Term__c/fields/FS_Community_Group_Member__c.field-meta.xml
<CustomField>
    <fullName>FS_Community_Group_Member__c</fullName>
    <label>Community Group Member</label>
    <referenceTo>PagesApi__Community_Group_Member__c</referenceTo>
    <relationshipLabel>Community Group Member Terms</relationshipLabel>
    <relationshipName>Community_Group_Member_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/FS_Community_Group_Member_Term__c/fields/FS_Deactivated_Manually__c.field-meta.xml
<CustomField>
    <fullName>FS_Deactivated_Manually__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivated Manually</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/FS_Community_Group_Member_Term__c/fields/FS_Term_End_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Term_End_Date__c</fullName>
    <description>The end date for community group member term</description>
    <inlineHelpText>The end date for community group member term</inlineHelpText>
    <label>Term End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/FS_Community_Group_Member_Term__c/fields/FS_Term_Grace_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Term_Grace_Period_End_Date__c</fullName>
    <inlineHelpText>Grace Period End Date is based off the related Subscription Term's Grace Period End Date</inlineHelpText>
    <label>Term Grace Period End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/FS_CommunityGroupMemberDrop.cls
/**
 * @author Christopher Mudd from fusionSpan
 * @date 2019-10-17.
 *
 * @description When a Contact drops their membership, deactivate all community group members for that contact
 */

global without sharing class FS_CommunityGroupMemberDrop extends Framework.Domain {

    private static final String ACTIVE_STRING = 'Active';
    private static final String GRACE_STRING = 'Grace';

    public FS_CommunityGroupMemberDrop(List<Contact> sObjectList) {
        super(sObjectList);
    }

    global class Constructor implements Framework.Domain.DomainConstructor {
        global Framework.Domain construct(List<SObject> sObjectList) {
            return new FS_CommunityGroupMemberDrop(sObjectList);
        }
    }

    global virtual override void afterUpdate(Map<Id, SObject> existingRecords) {

        Framework.Log.push(FS_CommunityGroupMemberDrop.class.getName(), 'afterUpdate');
        handleAfterUpdate((Map<Id, Contact>) existingRecords, (List<Contact>) records);
        Framework.Log.pop();

    }

    private static void handleAfterUpdate(Map<Id, Contact> oldMembersById, List<Contact> updatedMembers) {
        List<String> expiredContactIds = new List<String>();

        // check if the Contact is a member. If not, add to list for querying Community Group Members to deactivate
        for (Contact member : updatedMembers) {
            Contact oldMember = oldMembersById.get(member.Id);
//            if (oldMember.FS_Member_Status__c != NON_MEMBER_STRING && member.FS_Member_Status__c == NON_MEMBER_STRING) {
            if ((oldMember.FS_Contact_Member_Status__c == ACTIVE_STRING || oldMember.FS_Contact_Member_Status__c == GRACE_STRING) && (member.FS_Contact_Member_Status__c != ACTIVE_STRING && member.FS_Contact_Member_Status__c != GRACE_STRING)) {
                expiredContactIds.add(oldMember.Id);
            }
        }

        //Query for Community Group Members to deactivate
        List<PagesApi__Community_Group_Member__c> membersToDeactivate = [SELECT Id,PagesApi__Contact__c,PagesApi__Is_Active__c,FS_Grace_Period_End_Date__c,FS_Paid_Through_Date__c
                FROM PagesApi__Community_Group_Member__c WHERE PagesApi__Contact__c IN :expiredContactIds];

        Map<Id, PagesApi__Community_Group_Member__c> membersToUpdate = new Map<Id, PagesApi__Community_Group_Member__c>();
        for (PagesApi__Community_Group_Member__c member : membersToDeactivate) {
            member.PagesApi__Is_Active__c = false;
            member.FS_Term_End_Date__c = System.today();
            member.FS_Grace_Period_End_Date__c = null;
            member.FS_Paid_Through_Date__c = System.today();
            membersToUpdate.put(member.Id, member);
        }

        List<FS_Community_Group_Member_Term__c> termsToDeactivate = [
                SELECT Id,FS_Term_End_Date__c,FS_Term_Grace_Period_End_Date__c,FS_Deactivated_Manually__c
                FROM FS_Community_Group_Member_Term__c
                WHERE FS_Community_Group_Member__c IN :membersToUpdate.keySet()
        ];

        for (FS_Community_Group_Member_Term__c term : termsToDeactivate) {
            term.FS_Term_End_Date__c = System.today();
            term.FS_Term_Grace_Period_End_Date__c = null;
            term.FS_Deactivated_Manually__c = true;
        }

        update termsToDeactivate;
        update membersToUpdate.values();
    }
}