unpackaged/main/default/objects/Contact/fields/FS_Designation__c.field-meta.xml
<CustomField>
    <fullName>FS_Designation__c</fullName>
    <label>Designation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Esq.</fullName>
            </value>
            <value>
                <fullName>J.D.</fullName>
            </value>
            <value>
                <fullName>Advocate</fullName>
            </value>
            <value>
                <fullName>Barrister</fullName>
            </value>
            <value>
                <fullName>Solicitor</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>D.D.S.</fullName>
            </value>
            <value>
                <fullName>LL.M.</fullName>
            </value>
            <value>
                <fullName>M.D.</fullName>
            </value>
            <value>
                <fullName>Ph.D.</fullName>
            </value>
            <value>
                <fullName>QC</fullName>
            </value>
            <value>
                <fullName>Ret.</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>P.C.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FS_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>FS_Full_Name__c</fullName>
    <description>Auto-Calculated Field to display full name including designation and salutation</description>
    <inlineHelpText>Auto-Calculated Field to display full name including designation and salutation</inlineHelpText>
    <label>Full Name (Formal)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FS_Other_Designation__c.field-meta.xml
<CustomField>
    <fullName>FS_Other_Designation__c</fullName>
    <inlineHelpText>If your preferred designation does not appear in the list, you may provide it here (optional)</inlineHelpText>
    <label>Other Designation</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FS_Other_Salutation__c.field-meta.xml
<CustomField>
    <fullName>FS_Other_Salutation__c</fullName>
    <inlineHelpText>Other Salutation(if applicable)</inlineHelpText>
    <label>Other Salutation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/FS_ContactFullNameInsertUpdate.cls
global class FS_ContactFullNameInsertUpdate extends Framework.Domain {
    public FS_ContactFullNameInsertUpdate(List<Contact> sObjectList) {
        super(sObjectList);
    }
    
    global class Constructor implements Framework.Domain.DomainConstructor  {
        global Framework.Domain construct(List<Contact> sObjectList) {
            return new FS_ContactFullNameInsertUpdate(sObjectList);
        }
    }
    
    public override void beforeInsert() {
        Framework.Log.push(FS_ContactFullNameInsertUpdate.class.getName(),'Before Insert');
        updatingFullName((Contact[]) records);
        Framework.Log.pop();
    }
    
    public override void beforeUpdate(Map<Id, SObject> oldMap) {
        Framework.Log.push(FS_ContactFullNameInsertUpdate.class.getName(),'Before update');
        List<Contact> contactList = (List<Contact>) records;
        List<Contact> conList = new List<Contact>();
        for (Contact con : contactList) {
            Contact oldCon = (Contact)oldMap.get(con.Id);
            if(con.FirstName != oldCon.FirstName ||con.MiddleName != oldCon.MiddleName ||con.LastName != oldCon.LastName  
               || con.DonorApi__Suffix__c != oldCon.DonorApi__Suffix__c ||con.FS_Designation__c != oldCon.FS_Designation__c
               || con.FS_Other_Designation__c != oldCon.FS_Other_Designation__c || con.Salutation != oldCon.Salutation || 
               con.FS_Other_Salutation__c !=oldCon.FS_Other_Salutation__c || con.MiddleName != oldCon.MiddleName){
                   conList.add(con);
               }
            
        }
        updatingFullName(conList);
        Framework.Log.pop();
    }
    private static void updatingFullName(List<Contact> records){
        for(Contact con : records){
            if(con.LastName != null){	
                String fullName = '';  
                if(String.isNotBlank(con.FS_Designation__c) || String.isNotBlank(con.FS_Other_Designation__c)){
                    String designation = '';
                    if(String.isNotBlank(con.FS_Designation__c)){
                        if(con.FS_Designation__c.indexOf(';') >= 0){
                            designation = con.FS_Designation__c.replaceAll(';',', ');
                        }else{
                            designation = con.FS_Designation__c;
                        }   
                    }else if(String.isNotBlank(con.FS_Other_Designation__c)){
                        designation = con.FS_Other_Designation__c;
                    }
                    fullName = (String.isNotBlank(con.FirstName) ? con.FirstName +' ' : '') + (String.isNotBlank(con.MiddleName) ? con.MiddleName +' ' : '') + con.LastName +', ' +
                    (String.isNotBlank(con.DonorApi__Suffix__c) ? con.DonorApi__Suffix__c +', ' : '') + designation;
                }else{
                    fullName = (String.isNotBlank(con.Salutation) ? con.Salutation +' ' : (String.isNotBlank(con.FS_Other_Salutation__c) ? con.FS_Other_Salutation__c +' ' : '')) +
                        (String.isNotBlank(con.FirstName) ? con.FirstName +' ' : '') + (String.isNotBlank(con.MiddleName) ? con.MiddleName +' ' : '') + con.LastName  + 
                        (String.isNotBlank(con.DonorApi__Suffix__c) ? ', '+con.DonorApi__Suffix__c +' ' : '') + '';
                }
                con.FS_Full_Name__c = fullName;
            }
        }
    }
}