unpackaged/main/default/objects/Contact/fields/FS_Primary_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>FS_Primary_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Affiliation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FS_Primary_Affiliation_Record__c.field-meta.xml
<CustomField>
    <fullName>FS_Primary_Affiliation_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is automatically populated to link to the active Affiliation Record that is marked as Primary</description>
    <inlineHelpText>This field is automatically populated to link to the active Affiliation Record that is marked as Primary</inlineHelpText>
    <label>Primary Affiliation Record</label>
    <referenceTo>FS_Affiliation__c</referenceTo>
    <relationshipLabel>Contacts (Primary Affiliation Record)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FS_Affiliation__c/FS_Affiliation__c.object-meta.xml
<CustomObject>
    <description>An Affiliation links Accounts and Contacts. It defines relationships between companies and employees, relationships amongst employees etc</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>Affiliation {0000000}</displayFormat>
        <label>Affiliation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FS_Affiliation__c/fields/FS_Child_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Child_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contact affiliated to the company account</inlineHelpText>
    <label>Child Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parent Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FS_Affiliation__c/fields/FS_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>FS_Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Company Account affiliated to the contact</inlineHelpText>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Child Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FS_Affiliation__c/fields/FS_Primary_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>FS_Primary_Affiliation__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Primary affiliation of the contact</inlineHelpText>
    <label>Primary Affiliation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/FS_Affiliation__c/fields/FS_PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>FS_PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Primary contact of the firm/company</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/FS_Affiliation__c/fields/FS_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Status__c</fullName>
    <inlineHelpText>Status of the affiliation between the company and contact</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/FS_PrimaryAffiliationUpdateTest.cls
@IsTest
private class FS_PrimaryAffiliationUpdateTest {

    @TestSetup
    private static void install() {

        Framework.Installer.install();
        PagesApi.PackageScripts.install();
        OrderApi.PackageScripts.install();
        EventApi.PackageScripts.install();
        ROEApi.PackageScripts.install();
        CPBase.PackageScripts.install();
        LTE.PackageScripts.install();
        FDService.BUPackageScripts.install();
        DonorApi.PackageScripts.install();
        joinapi.PackageScripts.install();
        ProgramApi.PackageScripts.install();
        PriceApi.PackageScripts.install();
        DRCTS.PackageScripts.install();

        Framework.RoutingRule[] rules = new List<Framework.RoutingRule>();
        Framework.RoutingRule routingRule = new Framework.RoutingRule();
        routingRule.apexClass = FS_PrimaryAffiliationUpdateRule.class.getName();
        routingRule.namespace = '';
        routingRule.isEnabled = true;
        routingRule.sObjectName = 'FS_Affiliation__c';
        routingRule.executionOrder = 10;
        rules.add(routingRule);
        Framework.Config.push(rules);

        Account acc = new Account(
                Name = 'Tadesasd1234aszt Aasd1fccount');
        insert acc;
        //Inserting Contact
        Contact con = new Contact(
                LastName = 'tesavzvt',
                FirstName = 'conxzcwq2tact',
                Title = 'Manager',
                AccountId = acc.Id);
        insert con;
    }
    @IsTest
    private static void testPrimaryAffiliationOnContact() {
        //Inserting Account
        Account acc = [SELECT Id FROM Account WHERE Name = 'Tadesasd1234aszt Aasd1fccount'][0];
        //Inserting Contact
        Contact con = [SELECT Id FROM Contact WHERE LastName='tesavzvt'][0];


        //Inserting Affiliation with Account and Contact
        List<FS_Affiliation__c> affiliationList = new List<FS_Affiliation__c>();
        FS_Affiliation__c affiliation = new FS_Affiliation__c(
                FS_Parent_Account__c = acc.Id,
                FS_Child_Contact__c = con.Id,
                FS_Primary_Affiliation__c = true,
                FS_Status__c = 'Active',
                FS_PrimaryContact__c = true);
        affiliationList.add(affiliation);
        FS_PrimaryAffiliationUpdateRule controller = new FS_PrimaryAffiliationUpdateRule(affiliationList);
        controller.beforeInsert();
        insert affiliationList;
        controller.afterInsert();

        Test.startTest();

        List<Account> parentAccount = [SELECT Id,OrderApi__Primary_Contact__c FROM Account WHERE Id = :affiliation.FS_Parent_Account__c LIMIT 1];
        List<Contact> childAccount = [SELECT Id,FS_Primary_Affiliation__c,FS_Primary_Affiliation_Record__c FROM Contact WHERE Id = :affiliation.FS_Child_Contact__c LIMIT 1];

        System.assertEquals(affiliation.FS_Parent_Account__c, childAccount[0].FS_Primary_Affiliation__c);
        System.assertEquals(affiliation.FS_Child_Contact__c, parentAccount[0].OrderApi__Primary_Contact__c);
        System.assertEquals(affiliation.Id, childAccount[0].FS_Primary_Affiliation_Record__c);

        affiliation.FS_Status__c = 'Inactive';
        controller.beforeUpdate(new Map<Id, FS_Affiliation__c>{
                affiliation.Id => affiliation
        });
        if (affiliation.FS_Primary_Affiliation__c) {
            affiliation.FS_Primary_Affiliation__c = false;
        }
        update affiliation;
        affiliation.FS_Status__c = 'Active';
        affiliation.FS_Primary_Affiliation__c = true;
        controller.afterUpdate(new Map<Id, FS_Affiliation__c>{
                affiliation.Id => affiliation
        });

        Test.stopTest();


        parentAccount = [SELECT Id,OrderApi__Primary_Contact__c FROM Account WHERE Id = :affiliation.FS_Parent_Account__c LIMIT 1];
        childAccount = [SELECT Id,FS_Primary_Affiliation__c,FS_Primary_Affiliation_Record__c FROM Contact WHERE Id = :affiliation.FS_Child_Contact__c LIMIT 1];

        System.assertEquals(null, childAccount[0].FS_Primary_Affiliation__c);
        System.assertEquals(null, parentAccount[0].OrderApi__Primary_Contact__c);
        System.assertEquals(null, childAccount[0].FS_Primary_Affiliation_Record__c);
    }
}