unpackaged/main/default/objects/FS_Leadership_Role_and_Title__c/FS_Leadership_Role_and_Title__c.object-meta.xml
<CustomObject>
    <description>Child object of the Community Group Member, will hold leadership roles and titles</description>
    <label>Leadership Role and Title</label>
    <nameField>
        <displayFormat>LN-{000000}</displayFormat>
        <label>Leadership Role and Title Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leadership Roles and Titles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FS_Leadership_Role_and_Title__c/fields/FS_Leadership_Role__c.field-meta.xml
<CustomField>
    <fullName>FS_Leadership_Role__c</fullName>
    <description>Leadership Role for the Community Group Member during this time period</description>
    <inlineHelpText>Leadership Role for the Community Group Member during this time period</inlineHelpText>
    <label>Leadership Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>010 - President</fullName>
            </value>
            <value>
                <fullName>020 - Chair</fullName>
            </value>
            <value>
                <fullName>030 - Chair-Elect</fullName>
            </value>
            <value>
                <fullName>040 - Vice-Chair</fullName>
            </value>
            <value>
                <fullName>050 - Treasurer</fullName>
            </value>
            <value>
                <fullName>060 - Financial Officer</fullName>
            </value>
            <value>
                <fullName>070 - Secretary</fullName>
            </value>
            <value>
                <fullName>080 - Delegate</fullName>
            </value>
            <value>
                <fullName>090 - Alternate</fullName>
            </value>
            <value>
                <fullName>110 - District Representative</fullName>
            </value>
            <value>
                <fullName>120 - Former Chair</fullName>
            </value>
            <value>
                <fullName>130 - Ex-Officio Member</fullName>
            </value>
            <value>
                <fullName>140 - Honorary Member</fullName>
            </value>
            <value>
                <fullName>160 - Other</fullName>
            </value>
            <value>
                <fullName>170 - Internal (NYSBA) Group Liaison</fullName>
            </value>
            <value>
                <fullName>180 - External Group Liaison</fullName>
            </value>
            <value>
                <fullName>190 - Non-Attorney Advisor</fullName>
            </value>
            <value>
                <fullName>200 - Staff Liaison</fullName>
            </value>
            <value>
                <fullName>210 - CLE Staff Liaison</fullName>
            </value>
            <value>
                <fullName>999 - Unmapped Legacy Position</fullName>
            </value>
            <value>
                <fullName>220 - Distribution List Only</fullName>
            </value>
            <value>
                <fullName>100 - Member</fullName>
                <isActive>false</isActive>
                <label>100 - Member</label>
            </value>
            <value>
                <fullName>150 - Student Member</fullName>
                <isActive>false</isActive>
                <label>150 - Student Member</label>
            </value>
            <value>
                <fullName>Council Director</fullName>
                <isActive>false</isActive>
                <label>Council Director</label>
            </value>
            <value>
                <fullName>Executive Committee</fullName>
                <isActive>false</isActive>
                <label>Executive Committee</label>
            </value>
            <value>
                <fullName>MSS</fullName>
                <isActive>false</isActive>
                <label>MSS</label>
            </value>
            <value>
                <fullName>Manager</fullName>
                <isActive>false</isActive>
                <label>Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/FS_Leadership_Role_and_Title__c/fields/FS_Leadership_Title__c.field-meta.xml
<CustomField>
    <fullName>FS_Leadership_Title__c</fullName>
    <description>Leadership Title for this Leadership Role and Title during this time period</description>
    <inlineHelpText>Leadership Title for this Leadership Role and Title  during this time period</inlineHelpText>
    <label>Leadership Title</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/FS_RollUpLeadershipRoleAndTitleService.cls
public class FS_RollUpLeadershipRoleAndTitleService {
    public static void addOrUpdateRolesAndTitles(List<PagesApi__Community_Group_Member__c> cgmList){
        if(cgmList != null && !cgmList.isEmpty()){
            List<PagesApi__Community_Group_Member__c> updateCGMList = new List<PagesApi__Community_Group_Member__c>();
            for(PagesApi__Community_Group_Member__c cgm : cgmList){
                if(cgm.Leadership_Roles_and_Titles__r != null && !cgm.Leadership_Roles_and_Titles__r.isEmpty()){
                    List<String> updateRolesList = new List<String>();
                    List<String> updateTitlesList = new List<String>();
                    for(FS_Leadership_Role_and_Title__c roleAndTitle : cgm.Leadership_Roles_and_Titles__r){
                        updateRolesList.add(roleAndTitle.FS_Leadership_Role__c);
                        updateTitlesList.add(roleAndTitle.FS_Leadership_Title__c);
                    }
                    
                    updateCGMList.add(new PagesApi__Community_Group_Member__c(Id = cgm.Id, FS_Member_Role__c = String.join(updateRolesList,';'),
                                                                             FS_Leadership_Title__c = String.join(updateTitlesList,',')));
                }else{
                    updateCGMList.add(new PagesApi__Community_Group_Member__c(Id = cgm.Id, FS_Member_Role__c = '', FS_Leadership_Title__c = '')); 
                } 
            }
            if(!updateCGMList.isEmpty()){
                update updateCGMList;
            }
        }
    }
}