unpackaged/main/default/objects/FS_Leadership_Role_and_Title__c/FS_Leadership_Role_and_Title__c.object-meta.xml
<CustomObject>
    <description>Child object of the Community Group Member, will hold leadership roles and titles</description>
    <label>Leadership Role and Title</label>
    <nameField>
        <displayFormat>LN-{000000}</displayFormat>
        <label>Leadership Role and Title Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leadership Roles and Titles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FS_Leadership_Role_and_Title__c/fields/FS_Community_Group_Member__c.field-meta.xml
<CustomField>
    <fullName>FS_Community_Group_Member__c</fullName>
    <description>Linked to the Community Group Member</description>
    <inlineHelpText>Linked to the Community Group Member</inlineHelpText>
    <label>Community Group Member</label>
    <referenceTo>PagesApi__Community_Group_Member__c</referenceTo>
    <relationshipLabel>Leadership Roles and Titles</relationshipLabel>
    <relationshipName>Leadership_Roles_and_Titles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/FS_Leadership_Role_and_Title__c/fields/FS_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>FS_Is_Active__c</fullName>
    <description>Checkbox is True if Today's date falls in between Start Date and End Date</description>
    <formula>IF(AND(FS_Start_Date__c &lt;= TODAY(), FS_End_Date__c &gt;= TODAY()),true,IF(AND(FS_Start_Date__c &lt;= TODAY(), ISBLANK (FS_End_Date__c)), true, false))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Checkbox is True if Today's date falls in between Start Date and End Date</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/FS_Leadership_Role_and_Title__c/fields/FS_Leadership_Role__c.field-meta.xml
<CustomField>
    <fullName>FS_Leadership_Role__c</fullName>
    <description>Leadership Role for the Community Group Member during this time period</description>
    <inlineHelpText>Leadership Role for the Community Group Member during this time period</inlineHelpText>
    <label>Leadership Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>010 - President</fullName>
            </value>
            <value>
                <fullName>020 - Chair</fullName>
            </value>
            <value>
                <fullName>030 - Chair-Elect</fullName>
            </value>
            <value>
                <fullName>040 - Vice-Chair</fullName>
            </value>
            <value>
                <fullName>050 - Treasurer</fullName>
            </value>
            <value>
                <fullName>060 - Financial Officer</fullName>
            </value>
            <value>
                <fullName>070 - Secretary</fullName>
            </value>
            <value>
                <fullName>080 - Delegate</fullName>
            </value>
            <value>
                <fullName>090 - Alternate</fullName>
            </value>
            <value>
                <fullName>110 - District Representative</fullName>
            </value>
            <value>
                <fullName>120 - Former Chair</fullName>
            </value>
            <value>
                <fullName>130 - Ex-Officio Member</fullName>
            </value>
            <value>
                <fullName>140 - Honorary Member</fullName>
            </value>
            <value>
                <fullName>160 - Other</fullName>
            </value>
            <value>
                <fullName>170 - Internal (NYSBA) Group Liaison</fullName>
            </value>
            <value>
                <fullName>180 - External Group Liaison</fullName>
            </value>
            <value>
                <fullName>190 - Non-Attorney Advisor</fullName>
            </value>
            <value>
                <fullName>200 - Staff Liaison</fullName>
            </value>
            <value>
                <fullName>210 - CLE Staff Liaison</fullName>
            </value>
            <value>
                <fullName>999 - Unmapped Legacy Position</fullName>
            </value>
            <value>
                <fullName>220 - Distribution List Only</fullName>
            </value>
            <value>
                <fullName>100 - Member</fullName>
                <isActive>false</isActive>
                <label>100 - Member</label>
            </value>
            <value>
                <fullName>150 - Student Member</fullName>
                <isActive>false</isActive>
                <label>150 - Student Member</label>
            </value>
            <value>
                <fullName>Council Director</fullName>
                <isActive>false</isActive>
                <label>Council Director</label>
            </value>
            <value>
                <fullName>Executive Committee</fullName>
                <isActive>false</isActive>
                <label>Executive Committee</label>
            </value>
            <value>
                <fullName>MSS</fullName>
                <isActive>false</isActive>
                <label>MSS</label>
            </value>
            <value>
                <fullName>Manager</fullName>
                <isActive>false</isActive>
                <label>Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/FS_Leadership_Role_and_Title__c/fields/FS_Leadership_Title__c.field-meta.xml
<CustomField>
    <fullName>FS_Leadership_Title__c</fullName>
    <description>Leadership Title for this Leadership Role and Title during this time period</description>
    <inlineHelpText>Leadership Title for this Leadership Role and Title  during this time period</inlineHelpText>
    <label>Leadership Title</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/FS_RollUpLeadershipAndTitleRoutingRule.cls
global without sharing class FS_RollUpLeadershipAndTitleRoutingRule extends Framework.Domain {
    public FS_RollUpLeadershipAndTitleRoutingRule(List<FS_Leadership_Role_and_Title__c> sObjectList) {
        super(sObjectList);
    }

    global class Constructor implements Framework.Domain.DomainConstructor  {
        global Framework.Domain construct(List<SObject> sObjectList) {
            return new FS_RollUpLeadershipAndTitleRoutingRule(sObjectList);
        }
    }

    public override void afterUpdate(Map<Id, SObject> oldMap){
        Framework.Log.push(FS_RollUpLeadershipAndTitleRoutingRule.class.getName(), 'afterUpdate');
        Set<Id> cgmIds=new Set<Id>();
        for(FS_Leadership_Role_and_Title__c roleAndTitle : (List<FS_Leadership_Role_and_Title__c>)records){
            FS_Leadership_Role_and_Title__c oldRoleAndTitle = (FS_Leadership_Role_and_Title__c)oldMap.get(roleAndTitle.Id);
            if((roleAndTitle.FS_Is_Active__c && (roleAndTitle.FS_Leadership_Role__c != oldRoleAndTitle.FS_Leadership_Role__c)
                || (roleAndTitle.FS_Leadership_Title__c != oldRoleAndTitle.FS_Leadership_Title__c)) ||
                	roleAndTitle.FS_Is_Active__c != oldRoleAndTitle.FS_Is_Active__c) {
                cgmIds.add(roleAndTitle.FS_Community_Group_Member__c);
            }
        }
        if(!cgmIds.isEmpty()){
            processRecords(cgmIds);
        }
        Framework.Log.pop();
    }

    public override void afterInsert(){
        Framework.Log.push(FS_RollUpLeadershipAndTitleRoutingRule.class.getName(), 'afterInsert');
        addOrUpdateRolesAndTitles((List<FS_Leadership_Role_and_Title__c>)records);
        Framework.Log.pop();
    }

    public override void afterDelete(){
        Framework.Log.push(FS_RollUpLeadershipAndTitleRoutingRule.class.getName(), 'afterDelete');
        addOrUpdateRolesAndTitles((List<FS_Leadership_Role_and_Title__c>)records);
        Framework.Log.pop();
    }

    private static void addOrUpdateRolesAndTitles(List<FS_Leadership_Role_and_Title__c> records){
        Set<Id> cgmIds=new Set<Id>();
        for(FS_Leadership_Role_and_Title__c roleAndTitle : records){
            if(roleAndTitle.FS_Is_Active__c) {
                cgmIds.add(roleAndTitle.FS_Community_Group_Member__c);
            }
        }
        if(!cgmIds.isEmpty()){
            processRecords(cgmIds);
        }
    }

    private static void processRecords(Set<Id> cgmIds){
        FS_RollUpLeadershipRoleAndTitleService.addOrUpdateRolesAndTitles([SELECT Id, (SELECT Id,FS_Leadership_Role__c, FS_Leadership_Title__c,
                                                                            FS_Community_Group_Member__c FROM Leadership_Roles_and_Titles__r
                                                                            WHERE FS_Is_Active__c = TRUE ORDER BY FS_Leadership_Role__c)
                                                                          FROM PagesApi__Community_Group_Member__c WHERE Id IN : cgmIds
                                                                          AND PagesApi__Status__c = 'Active' AND PagesApi__Contact__c != NULL ]);
    }
}