unpackaged/main/default/objects/API_Settings__mdt/API_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Has the endpoint and authentication details for integrations</description>
    <label>API Settings</label>
    <pluralLabel>API Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/API_Settings__mdt/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Netsuite Account.Company identifier</description>
    <label>Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/API_Settings__mdt/fields/Consumer_Key__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Key__c</fullName>
    <description>Consumer Key</description>
    <label>Consumer Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/API_Settings__mdt/fields/Consumer_Secret__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Secret__c</fullName>
    <description>Consumer Secret</description>
    <label>Consumer Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/API_Settings__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint url</description>
    <label>Endpoint</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/API_Settings__mdt/fields/Token_Id__c.field-meta.xml
<CustomField>
    <fullName>Token_Id__c</fullName>
    <description>Token Id</description>
    <label>Token Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/API_Settings__mdt/fields/Token_Secret__c.field-meta.xml
<CustomField>
    <fullName>Token_Secret__c</fullName>
    <description>Token Secret</description>
    <label>Token Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/JSON_Mapping__mdt/JSON_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>JSON mapping for different payloads</description>
    <label>JSON Mapping</label>
    <pluralLabel>JSON Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/JSON_Mapping__mdt/fields/Child_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_Object_API_Name__c</fullName>
    <description>APi name of the child object</description>
    <label>Child Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/JSON_Mapping__mdt/fields/Data_type__c.field-meta.xml
<CustomField>
    <fullName>Data_type__c</fullName>
    <description>Data type of the field value</description>
    <label>Data type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Boolean</fullName>
                <default>true</default>
                <label>Boolean</label>
            </value>
            <value>
                <fullName>String</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/JSON_Mapping__mdt/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <description>Default value of the current node</description>
    <label>Default</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/JSON_Mapping__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>API name of the salesforce field</description>
    <label>Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/JSON_Mapping__mdt/fields/Filter_Field__c.field-meta.xml
<CustomField>
    <fullName>Filter_Field__c</fullName>
    <description>API name on the child object field that is to be used to filter records</description>
    <label>Filter Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/JSON_Mapping__mdt/fields/Filter_Field_Datatype__c.field-meta.xml
<CustomField>
    <fullName>Filter_Field_Datatype__c</fullName>
    <description>Data type of the filter field</description>
    <label>Filter Field Datatype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/JSON_Mapping__mdt/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <description>Grouping fields of complex type in case multiple instances need to be created of the same complex type that are mapped to different salesforce fields.</description>
    <label>Group</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/JSON_Mapping__mdt/fields/JSON_Node__c.field-meta.xml
<CustomField>
    <fullName>JSON_Node__c</fullName>
    <description>Node name of JSON</description>
    <label>JSON Node</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/JSON_Mapping__mdt/fields/Null_Check_field__c.field-meta.xml
<CustomField>
    <fullName>Null_Check_field__c</fullName>
    <description>this field is used to check a different field value which if null stops the current node from being rendered.</description>
    <label>Null Check field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/JSON_Mapping__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>API name of the object</description>
    <label>Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/JSON_Mapping__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Nesting order in json</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/JSON_Mapping__mdt/fields/Parent_Node__c.field-meta.xml
<CustomField>
    <fullName>Parent_Node__c</fullName>
    <description>Name of parent json node</description>
    <label>Parent Node</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/JSON_Mapping__mdt/fields/Type_of_Node__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Node__c</fullName>
    <description>Whether the current JSON node is a complex structure(Map), list of elements(List)  or a simple key-value pair(Simple)</description>
    <label>Type of Node</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Simple</fullName>
                <default>true</default>
                <label>Simple</label>
            </value>
            <value>
                <fullName>Map</fullName>
            </value>
            <value>
                <fullName>List</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Sync_Settings__mdt/Sync_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Sync Settings</label>
    <pluralLabel>Sync Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Sync_Settings__mdt/fields/Child_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_Object_API_Name__c</fullName>
    <description>API name of the child object to be included in payload</description>
    <label>Child Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sync_Settings__mdt/fields/Object_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Object_Endpoint__c</fullName>
    <description>Object specific URL to be appended to the endpoint</description>
    <label>Object Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sync_Settings__mdt/fields/SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Name__c</fullName>
    <description>SObject API Name</description>
    <label>SObject Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sync_Settings__mdt/fields/Sync_Child_Records__c.field-meta.xml
<CustomField>
    <fullName>Sync_Child_Records__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes if any child records are to be pushed along with parent payload</description>
    <label>Sync Child Records?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Sync_Settings__mdt/fields/Sync_Type__c.field-meta.xml
<CustomField>
    <fullName>Sync_Type__c</fullName>
    <label>Sync Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real-time</fullName>
                <default>true</default>
                <label>Real-time</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/Plative_SFToNSSyncBatch.cls
/**
* Company     : Plative
* Description : Generic Batch class to sync data from Salesforce to Netsuite.
*               Batch size to be set is 10.
* [27.May.2020] Anisa - Code Creation 
*/
global class Plative_SFToNSSyncBatch implements Database.Batchable<SObject>,Database.AllowsCallouts {
    
    String sObjectApiName = '';
    List<Sync_Settings__mdt> syncSettings;
    
    global Plative_SFToNSSyncBatch(String sObjectApiName){
        this.sObjectApiName = sObjectApiName;
        //Fetch the field that needs to be checked against the object 
        if(String.isNotBlank(sObjectApiName)){
            syncSettings = [SELECT Id,Object_Endpoint__c
							FROM Sync_Settings__mdt 
                            WHERE SObject_Name__c = :sObjectApiName 
							AND Sync_Type__c IN ('Scheduled','Both')];
        }
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        //if Field for Sync on the object is found fetch the field mappings.
        if(syncSettings != null && !syncSettings.isEmpty()){
            //Fetch the fields that need to be checked for any change 
            List<JSON_Mapping__mdt> lstFieldMappingMetaData = [SELECT Default__c,Field_API_Name__c,
                                                                       Group__c,JSON_Node__c,Object_API_Name__c,
                                                                       Order__c,Parent_Node__c,Type_of_Node__c,
                                                                       Data_type__c,Child_Object_API_Name__c,
                                                                       Null_Check_field__c, Filter_Field__c,
																	   Filter_Field_Datatype__c, Filter_Value__c 
                                                               FROM JSON_Mapping__mdt 
                                                               WHERE Object_API_Name__c = :sObjectApiName];
            String query;
            if(!lstFieldMappingMetaData.isEmpty()){
                query = Plative_SFToNSSyncUtility.createQueryFromMapping(sObjectApiName,
                                                                         lstFieldMappingMetaData);
                query += ' WHERE Sync_To_Netsuite__c = TRUE';
            }
            if(!String.isBlank(query)){
                return Database.getQueryLocator(query);
            }
        }
        return null;     
       
    }
    global void execute(Database.BatchableContext bc, List<SObject> scope){
        // process each batch of records
        system.debug('scope: ' + scope);
        Set<Id> setIds = new Set<Id>();

        for(SObject sobj : scope){
            setIds.add((Id)sobj.get('Id'));
        }

        //Get API settings from custom metadata types
        List<API_Settings__mdt> apiSettings = [
                SELECT Consumer_Key__c, Consumer_Secret__c,
                        Endpoint__c,Token_Id__c, Token_Secret__c,
                        Account__c
                FROM API_Settings__mdt
                WHERE DeveloperName = 'Netsuite'
        ];
        //Check if sync settings exist
        Sync_Settings__mdt syncSetting = Plative_SFToNSSyncUtility.checkSyncSettings(this.sObjectApiName);
        List<SObject> lstChildSobjects;
        // Check if child records are to be sent in payload
        if(syncSetting.Sync_Child_Records__c){
            lstChildSobjects = Plative_SFToNSSyncUtility.getChildRecordsToSync(syncSetting,
                                                                            setIds,
                                                                            this.sObjectApiName); 
        }
        List<SObject> lstUnprocessedSobjects = Plative_SFToNSSyncUtility.upsertRecord(
                                               scope, lstChildSobjects,apiSettings, 
                                               syncSettings[0], false);
    }    
    global void finish(Database.BatchableContext bc){
        
    }  
}