unpackaged/main/default/objects/FS_Fellow__c/FS_Fellow__c.object-meta.xml
<CustomObject>
    <description>Custom object to track fellows information</description>
    <label>Fellow</label>
    <nameField>
        <displayFormat>Fellow {000000}</displayFormat>
        <label>Fellow ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FS_Fellow__c/fields/FS_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contact opted into the fellows donation program</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fellows</relationshipLabel>
    <relationshipName>Fellows</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FS_FellowsTest.cls
@Istest
public class FS_FellowsTest {
       @TestSetup
      private static void install() {
          Framework.Installer.install();
          PagesApi.PackageScripts.install();
          OrderApi.PackageScripts.install();

          Framework.RoutingRule[] rules = new List<Framework.RoutingRule>();
          Framework.RoutingRule FS_FellowsRule = new Framework.RoutingRule();
          FS_FellowsRule.apexClass = FS_Fellows.class.getName();
          FS_FellowsRule.namespace = '';
          FS_FellowsRule.isEnabled = true;
          FS_FellowsRule.sObjectName = 'FS_Fellow__c';
          FS_FellowsRule.executionOrder = 10;
          rules.add(FS_FellowsRule);
          Framework.Config.push(rules);
      }
 @Istest
      static void fellowsTestInsert(){
          //Inserting Contact
          Contact con =new Contact();
          con.LastName = 'Test Contact';
          insert con;
          
          //inserting Fellow
          FS_Fellow__c fellow = new FS_Fellow__c(FS_Contact__c=con.Id);
          insert fellow;
          
          
          List<FS_Fellow__c> fellowList = [SELECT Id FROM FS_Fellow__c WHERE Id=:fellow.Id];
          FS_Fellows FSFellowRoutingRule = new FS_Fellows(fellowList);
          FS_Fellows.Constructor cons = new FS_Fellows.Constructor();
          cons.construct(fellowList);
          Framework.Dispatcher.dispatchTrigger();
          }
}