unpackaged/main/default/objects/FS_Fellow__c/FS_Fellow__c.object-meta.xml
<CustomObject>
    <description>Custom object to track fellows information</description>
    <label>Fellow</label>
    <nameField>
        <displayFormat>Fellow {000000}</displayFormat>
        <label>Fellow ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FS_Fellow__c/fields/FS_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contact opted into the fellows donation program</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fellows</relationshipLabel>
    <relationshipName>Fellows</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FS_Pledge_Installments__c/FS_Pledge_Installments__c.object-meta.xml
<CustomObject>
    <description>Custom object to track fellows pledge installmets</description>
    <label>Pledge Installments</label>
    <nameField>
        <displayFormat>PID {000000}</displayFormat>
        <label>Pledge Installment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pledge Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FS_Pledge_Installments__c/fields/FS_Fellow__c.field-meta.xml
<CustomField>
    <fullName>FS_Fellow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Fellow tied to the pledge installments</inlineHelpText>
    <label>Fellow</label>
    <referenceTo>FS_Fellow__c</referenceTo>
    <relationshipLabel>Pledge Installments</relationshipLabel>
    <relationshipName>Pledge_Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FS_Pledge_InstallmentsTest.cls
@IsTest
public class FS_Pledge_InstallmentsTest {
	@TestSetup
	private static void install() {
          Framework.Installer.install();
          PagesApi.PackageScripts.install();
          OrderApi.PackageScripts.install();

          Framework.RoutingRule[] rules = new List<Framework.RoutingRule>();
          Framework.RoutingRule pledgeInstallmentRule = new Framework.RoutingRule();
          pledgeInstallmentRule.apexClass = FS_Pledge_Installments.class.getName();
          pledgeInstallmentRule.namespace = '';
          pledgeInstallmentRule.isEnabled = true;
          pledgeInstallmentRule.sObjectName = 'FS_Pledge_Installments__c';
          pledgeInstallmentRule.executionOrder = 10;
          rules.add(pledgeInstallmentRule);
          Framework.Config.push(rules);
	}
    @IsTest
    static void pledgeInstallmentTestInsert(){
        //Inserting Contact
		Contact con =new Contact();
		con.LastName = 'Test Contact';
		insert con;
          
		//Inserting Fellow
		FS_Fellow__c fellow = new FS_Fellow__c(FS_Contact__c=con.Id);
		insert fellow;
        
        //Inserting Pledge Installation
        FS_Pledge_Installments__c pledgeInstallment = new FS_Pledge_Installments__c(FS_Fellow__c=fellow.Id);
        insert pledgeInstallment;
        
        List<FS_Pledge_Installments__c> pledgeInstallments = [SELECT Id FROM FS_Pledge_Installments__c WHERE Id =:pledgeInstallment.Id];
		FS_Pledge_Installments pledgeInstallmentRule = new FS_Pledge_Installments(pledgeInstallments);
        FS_Pledge_Installments.Constructor cons = new FS_Pledge_Installments.Constructor();
        cons.construct(pledgeInstallments);
        Framework.Dispatcher.dispatchTrigger();
    }
}