unpackaged/main/default/objects/FS_Awards__c/FS_Awards__c.object-meta.xml
<CustomObject>
    <description>Custom object to track contact awards</description>
    <label>Awards</label>
    <nameField>
        <displayFormat>Award {000000}</displayFormat>
        <label>Award ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FS_Awards__c/fields/FS_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contact tied to the Awards</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Awards</relationshipLabel>
    <relationshipName>Awards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FS_AwardsTest.cls
@IsTest
public class FS_AwardsTest {
@TestSetup
      private static void install() {
          Framework.Installer.install();
          PagesApi.PackageScripts.install();
          OrderApi.PackageScripts.install(); 

          Framework.RoutingRule[] rules = new List<Framework.RoutingRule>();
          Framework.RoutingRule FS_AwardsRule = new Framework.RoutingRule();
          FS_AwardsRule.apexClass = FS_Awards.class.getName();
          FS_AwardsRule.namespace = '';
          FS_AwardsRule.isEnabled = true;
          FS_AwardsRule.sObjectName = 'FS_Awards__c';
          FS_AwardsRule.executionOrder = 10;
          rules.add(FS_AwardsRule);
          Framework.Config.push(rules);
      }

      @istest
      static void awardsTestInsert(){
          Contact con =new Contact();
          con.LastName = 'Test Contact';
          insert con;
          
		  FS_Awards__c awards=new FS_Awards__c();
          awards.FS_Contact__c = con.Id;
          insert awards;
          
          List<FS_Awards__c> awardsList = [SELECT Id FROM FS_Awards__c WHERE Id=:awards.Id];
          FS_Awards FSAwardsRoutingRule = new FS_Awards(awardsList);
          FS_Awards.Constructor cons = new FS_Awards.Constructor();
          cons.construct(awardsList);
          Framework.Dispatcher.dispatchTrigger();
          }
}